[package]
name = "hogya"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies]
windows = { version = "0.58", features = ["Win32_System_Threading", "Win32_System_LibraryLoader", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_Security"] }